import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";

import { ChoiceChip, IconBadge, PrimaryButton, SectionTitle } from "@/components/nourish-ui";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useNourish } from "@/lib/nourish-context";
import type { DietaryOption } from "@/shared/nourish";

const dietLabels: { label: string; value: DietaryOption }[] = [{ label: "Vegetarian", value: "vegetarian" }, { label: "Vegan", value: "vegan" }, { label: "Dairy-free", value: "dairy-free" }, { label: "Gluten-free", value: "gluten-free" }];

export default function ProfileScreen() {
  const router = useRouter();
  const { preferences, setPreferences, hasPro } = useNourish();
  const toggleDiet = (dietary: DietaryOption) => { haptic.selection(); setPreferences({ ...preferences, dietary: preferences.dietary.includes(dietary) ? preferences.dietary.filter((item) => item !== dietary) : [...preferences.dietary, dietary] }); };
  return <ScreenContainer className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.kicker}>YOUR SETTINGS</Text><Text style={styles.title}>Keep it personal.</Text><Text style={styles.copy}>These choices help every idea feel a little more like yours.</Text></View><View style={styles.profileCard}><View style={styles.profileMark}><Text style={styles.profileLetter}>N</Text></View><View style={styles.profileText}><Text style={styles.profileTitle}>Your NourishLoop</Text><Text style={styles.profileCopy}>{hasPro ? "Plus member · expanded support unlocked" : "Free plan · flexible daily support"}</Text></View><MaterialCommunityIcons name="leaf" size={22} color="#1F5A4C" /></View><View style={styles.section}><SectionTitle eyebrow="Food preferences" title="I’d like ideas that are" /><View style={styles.dietChoices}>{dietLabels.map((option) => <ChoiceChip key={option.value} label={option.label} selected={preferences.dietary.includes(option.value)} onPress={() => toggleDiet(option.value)} />)}</View></View><View style={styles.section}><SectionTitle eyebrow="A little structure" title="Gentle reminders" /><View style={styles.settingRow}><IconBadge icon="bell-outline" /><View style={styles.settingText}><Text style={styles.settingTitle}>A kind nudge, when useful</Text><Text style={styles.settingCopy}>Keep supportive meal reminders turned on.</Text></View><Switch value={preferences.gentleReminders} onValueChange={(value) => { haptic.selection(); setPreferences({ ...preferences, gentleReminders: value }); }} trackColor={{ false: "#D7DBD7", true: "#83AA9A" }} thumbColor="#FFFFFF" /></View></View><View style={styles.plusCard}><View style={styles.plusTop}><IconBadge icon="creation" color="#A65F38" background="#FCE8DA" /><Text style={styles.plusLabel}>NOURISHLOOP PLUS</Text></View><Text style={styles.plusTitle}>{hasPro ? "Your extra support is ready." : "More support, never more pressure."}</Text><Text style={styles.plusCopy}>{hasPro ? "Use premium weekly collections and preference-rich ideas whenever you like." : "Unlock expanded meal collections, deeper ingredient swaps, and gentle weekly planning."}</Text><PrimaryButton label={hasPro ? "View your plan" : "Explore Plus"} onPress={() => router.push("/premium" as never)} icon="arrow-right" /></View><Pressable onPress={() => router.push("/premium" as never)} style={({ pressed }) => [styles.restore, pressed && styles.pressed]}><Text style={styles.restoreText}>Restore a previous purchase</Text></Pressable><Text style={styles.disclaimer}>NourishLoop offers general meal inspiration, not medical or dietary advice.</Text></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 14, paddingBottom: 30, gap: 25 }, header: { gap: 5 }, kicker: { color: "#1F5A4C", fontSize: 11, lineHeight: 15, fontWeight: "900", letterSpacing: 1.1 }, title: { color: "#21312B", fontSize: 30, lineHeight: 37, fontWeight: "800" }, copy: { color: "#6F8176", fontSize: 15, lineHeight: 21 }, profileCard: { backgroundColor: "#FFFFFF", borderRadius: 21, borderWidth: 1, borderColor: "#ECEDE8", padding: 16, flexDirection: "row", alignItems: "center", gap: 12 }, profileMark: { width: 43, height: 43, borderRadius: 15, backgroundColor: "#F3B284", alignItems: "center", justifyContent: "center" }, profileLetter: { color: "#21312B", fontSize: 18, fontWeight: "900" }, profileText: { flex: 1, gap: 2 }, profileTitle: { color: "#21312B", fontSize: 16, lineHeight: 21, fontWeight: "800" }, profileCopy: { color: "#6F8176", fontSize: 12, lineHeight: 17 }, section: { gap: 13 }, dietChoices: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, settingRow: { minHeight: 77, backgroundColor: "#FFFFFF", borderRadius: 20, borderWidth: 1, borderColor: "#ECEDE8", padding: 14, flexDirection: "row", gap: 11, alignItems: "center" }, settingText: { flex: 1, gap: 2 }, settingTitle: { color: "#21312B", fontSize: 15, lineHeight: 20, fontWeight: "800" }, settingCopy: { color: "#6F8176", fontSize: 12, lineHeight: 17 }, plusCard: { borderRadius: 23, padding: 18, gap: 10, backgroundColor: "#21312B" }, plusTop: { flexDirection: "row", alignItems: "center", gap: 10 }, plusLabel: { color: "#F3B284", fontSize: 11, lineHeight: 15, fontWeight: "900", letterSpacing: 1.05 }, plusTitle: { color: "#FFFFFF", fontSize: 21, lineHeight: 27, fontWeight: "800" }, plusCopy: { color: "#C3D1C9", fontSize: 14, lineHeight: 20, marginBottom: 4 }, restore: { alignSelf: "center", minHeight: 36, justifyContent: "center" }, restoreText: { color: "#1F5A4C", fontSize: 13, lineHeight: 18, fontWeight: "800", textDecorationLine: "underline" }, disclaimer: { color: "#87958D", fontSize: 11, lineHeight: 16, textAlign: "center", paddingHorizontal: 12 }, pressed: { opacity: 0.7 },
});
